{
 'cca': 'cca7',
 'jupyter': 'lab',
 'packages': ["pipe_tasks", "display_ds9",  "obs_subaru",
              "jointcal", "display_matplotlib -t nchotard"],
 'username': 'nchotard',
 'vstack': 'w_2017_38',
 'workdir': '/sps/lsst/dev/nchotard/demo/lsst_drp_analysis'
}