{
 'cca': 'cca7',
 'jupyter': 'lab',
 'packages': ["pipe_tasks", "display_ds9",  "obs_subaru",
              "jointcal", "display_matplotlib -t nchotard"],
 'username': 'nchotard',
 'vstack': 'w_2017_41',
 'workdir': '/sps/lsst/dev/lsstprod/clusters/test/'
 #'workdir': '/sps/lsst/dev/nchotard/demo/lsst_drp_analysis',
 #'libs': '/sps/lsst/dev/nchotard/demo/python3/lib/python3.6/site-packages',
 #'bins': '/sps/lsst/dev/nchotard/demo/python3/bin'
}