{
 'host': 'cca7.in2p3.fr',  # or ccjupyter if you have configured your ~/.ssh/config file
 'jupyter': 'lab',
 'packages': ["pipe_tasks", "display_ds9",  "obs_subaru",
              "jointcal", "display_matplotlib -t nchotard"],
 'username': 'nchotard',
 'vstack': 'w_2017_42',
 'workdir': '/sps/lsst/dev/nchotard/demo/lsst_drp_analysis',
 'libs': '/sps/lsst/dev/nchotard/demo/python3/lib/python3.6/site-packages',
 'bins': '/sps/lsst/dev/nchotard/demo/python3/bin',
}