{
 'default_config': 'host1',

 'host1': {
           'host': 'myhost.domain.fr',  # or 'myhost' if you have configured your ~/.ssh/config file
           'jupyter': 'lab',  # if installed
           'username': 'myusername',
           'mysetup': '/path/to/my/setup/file.sh',
           'workdir': '/path/to/my/directory/'
            },

 'host2': {
           'host': 'otherhost.fr',
           'username': 'otherusername',
           'mysetup': '/path/to/my/setup'
          },
}